Fix argument parsing
Specifying a `swagger-config-file` always caused error on [line 159](https://github.com/Legion2/swagger-ui-action/blob/2a197da30e4459827b3d285f36e2af13c44bccc5/src/swagger-ui-action.ts#L159).

```error
Error: Only one configuration input can be used to configure swagger-ui with this action.You specified "swaggerConfigFile" and "swaggerConfigUrl" at the same time!
```